config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users/new', to: 'users#create'
  get 'users/create'
  get 'users/:id', to: 'users#show'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'events/new', to: 'events#new'
  post 'events/new', to: 'events#create'
  get 'events/index', to: 'events#index'
  get 'events/:id', to: 'events#show'
  resources :users, only: [:new,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :event_attendees
  has_many :attendees, class_name: 'User', through: :event_attendees

  scope :upcoming, -> { where('date > ?', Time.now) }
  scope :past, -> { where('date < ?', Time.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: :user_id
  belongs_to :attended_event, class_name: 'Event', foreign_key: :event_id
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :email, :password, presence: true

  has_many :events
  has_many :event_attendees
  has_many :attended_event, class_name: 'Event', through: :event_attendees
  has_secure_password

  def upcoming_events
    attended_event.where('date > ?', Time.now)
  end

  def previous_events
    attended_event.where('date < ?', Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user
  attr_writer :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    if current_user.nil?
      false
    else
      true
    end
    # !!current_user
  end

  def require_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to events_index_path
    else
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :description, :venue)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(id: params[:session][:id])
    if user
      session[:user_id] = user.id
      redirect_to events_index_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    current_user = @user
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>

  <h2>Past Events</h2>
  <% Event.past.each do |event| %>
    <div class="card">
    <div class="card-body">
        <h3><%= event.title %></h3>
        <p>
            <%= event.description%>
        </p>
        <div class="badge badge-primary">
            Venue: <%= event.venue %>
        </div>
        <div class="badge badge-success">
            Date: <%= event.date %>
        </div>
      </div>
    </div>

  <% end %>

  <h2>Upcoming</h2>
  <% Event.upcoming.each do |event| %>
    <div class="card">
    <div class="card-body">
        <h3><%= event.title %></h3>
        <p>
            <%= event.description%>
        </p>
        <div class="badge badge-primary">
            Venue: <%= event.venue %>
        </div>
        <div class="badge badge-success">
            Date: <%= event.date %>
        </div>
      </div>
    </div>
  <% end %>
  

app/views/events/new.html.erb
    
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Create Event</h3>
    <%= form_for(@event,  url: events_new_path) do |f| %>
      <div class = "form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, placeholder: "Enter event title", class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :date %>
        <%= f.date_field :date, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :venue %>
        <%= f.text_field :venue, class: 'form-control' %>
      </div>
      <%= f.button "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
    <div class="card-body">
    <h3><%= @event.title %></h3>
    <div>
        Creator: <%= @event.creator.first_name %>
    </div>
    <br>
    <h4>Attendees</h4>
    <p><%= @event.description%></p>
    <ul>
      <% @attendees.each do |attendee| %>
          <li><%= attendee.first_name%></li>  
      <% end %>
    </ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Private Events</a>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="mr-3"><%= link_to 'Home', events_index_path %></li>
        <li class="mr-3"><%= link_to 'Create Event', events_new_path %></li>
        <li class="mr-3"><%= link_to 'My Events', user_path(current_user) %></li>
        <li class="mr-3"><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li class="badge badge-secondary"><%= current_user.first_name %></li>
      <% else %>
        <li class="mr-3"><%= link_to 'Log In', login_path %></li>
        <li><%= link_to 'Sign Up', users_new_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = 'container'>
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row">
      <div class="col-md-6 mx-auto">
        <h3>Sign Up</h3>
        <%= form_for(@user,  url: users_new_path) do |f| %>
          <div class = "form-group">
            <%= f.label :first_name, "First Name" %>
            <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>
          </div>
          <div class = "form-group">
            <%= f.label :last_name, "Last Name" %>
            <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>
          </div>
          <div class = "form-group">
            <%= f.label :email, "Email" %>
            <%= f.email_field :email, placeholder: "johndoe@ymail.com", class: 'form-control' %>
          </div>
          <div class = "form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class = "form-group">
            <%= f.label :password_confirmation, "Password Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.button "Submit", class: "btn btn-primary" %>
        <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>This is the User page</h1>

    <table class="table">

        <tr>
            <td>First Name:</td>
            <td> <%= @user.first_name %></td>
        </tr>
        <tr>
            <td>Last Name:</td>
            <td> <%= @user.last_name %></td>
        </tr>
        <tr>
            <td>Email:</td>
            <td> <%= @user.email %></td>
        </tr>
    </table>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="events-tab" data-toggle="tab" href="#events" role="tab" aria-controls="events" aria-selected="true">Organized Events</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="attending-tab" data-toggle="tab" href="#attending" role="tab" aria-controls="attending" aria-selected="false">Attended Events </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="upcoming-tab" data-toggle="tab" href="#upcoming" role="tab" aria-controls="upcoming" aria-selected="false">Upcoming Events </a>
    </li>
    
    </ul>
    <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="events" role="tabpanel" aria-labelledby="events-tab">
        <% @user.events.each do | event|%>
            <div class="card border-light mb-3">
                <div class="card-body">
                    <h3><%= event.title %></h3>
                    <p>
                        <%= event.description%>
                    </p>
                    <div class="badge badge-primary">
                        Venue: <%= event.venue %>
                    </div>
                    <div class="badge badge-success">
                        Date: <%= event.date %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="tab-pane fade" id="attending" role="tabpanel" aria-labelledby="attending-tab">
        
                <% @prev_events.each do |event|%>
                    <div class="card border-light mb-3">
                        <div class="card-body">
                            <h3><%= event.title %></h3>
                            <p>
                                <%= event.description%>
                            </p>
                            <div class="badge badge-primary">
                                Venue: <%= event.venue %>
                            </div>
                            <div class="badge badge-success">
                                Date: <%= event.date %>
                            </div>
                        </div>
                    </div>
                <% end %>
        
    </div>

    <div class="tab-pane fade" id="upcoming" role="tabpanel" aria-labelledby="upcoming-tab">
        
                <% @upcoming_events.each do |event|%>
                    <div class="card border-light mb-3">
                        <div class="card-body">
                            <h3><%= event.title %></h3>
                            <p>
                                <%= event.description%>
                            </p>
                            <div class="badge badge-primary">
                                Venue: <%= event.venue %>
                            </div>
                            <div class="badge badge-success">
                                Date: <%= event.date %>
                            </div>
                        </div>
                    </div>
                <% end %>
        
    </div>
    
    </div>